// Generated by docs/spikes/generator/emit.ts from tests/contract/snapshots/esi-openapi.snapshot.json. Do not edit.
import type { OperationMeta, Transport } from './transport';

export type StatusGet = {
  /** Current online player count */
  readonly players: number;
  /** Running version as string */
  readonly server_version: string;
  /** Server start timestamp */
  readonly start_time: string;
  /** If the server is in VIP mode */
  readonly vip?: boolean;
};

export type MarketsRegionIdOrdersGet = readonly ({
  readonly duration: number;
  readonly is_buy_order: boolean;
  readonly issued: string;
  readonly location_id: number;
  readonly min_volume: number;
  readonly order_id: number;
  readonly price: number;
  readonly range: "station" | "region" | "solarsystem" | "1" | "2" | "3" | "4" | "5" | "10" | "20" | "30" | "40";
  /** The solar system this order was placed */
  readonly system_id: number;
  readonly type_id: number;
  readonly volume_remain: number;
  readonly volume_total: number;
})[];

/** Wallet balance */
export type CharactersCharacterIdWalletGet = number;

export type CharacterID = number;

export type UniverseTypesTypeIdGet = {
  readonly capacity?: number;
  readonly description: string;
  readonly dogma_attributes?: readonly ({
  readonly attribute_id: number;
  readonly value: number;
})[];
  readonly dogma_effects?: readonly ({
  readonly effect_id: number;
  readonly is_default: boolean;
})[];
  readonly graphic_id?: number;
  readonly group_id: number;
  readonly icon_id?: number;
  /** This only exists for types that can be put on the market */
  readonly market_group_id?: number;
  readonly mass?: number;
  readonly name: string;
  readonly packaged_volume?: number;
  readonly portion_size?: number;
  readonly published: boolean;
  readonly radius?: number;
  readonly type_id: number;
  readonly volume?: number;
};

export type UniverseNamesPost = readonly ({
  readonly category: "alliance" | "character" | "constellation" | "corporation" | "inventory_type" | "region" | "solar_system" | "station" | "faction";
  readonly id: number;
  readonly name: string;
})[];

export const getStatusMeta: OperationMeta = {
  operationId: 'GetStatus',
  method: 'GET',
  path: '/status',
  scopes: [],
  paginated: false,
};

/**
 * Retrieve the uptime and player counts
 *
 * `GET /status`
 */
export function getStatus(transport: Transport): Promise<StatusGet> {
  return transport.request<StatusGet>(getStatusMeta, { path: {}, query: {} });
}

export interface GetMarketsRegionIdOrdersParams {
  /** Return orders in this region */
  readonly region_id: number;
  /** Filter buy/sell orders, return all orders by default. If you query without type_id, we always return both buy and sell orders */
  readonly order_type: "buy" | "sell" | "all";
  /** Return orders only for this type */
  readonly type_id?: number;
}

export const getMarketsRegionIdOrdersMeta: OperationMeta = {
  operationId: 'GetMarketsRegionIdOrders',
  method: 'GET',
  path: '/markets/{region_id}/orders',
  scopes: [],
  paginated: true,
};

/**
 * List orders in a region
 *
 * `GET /markets/{region_id}/orders`. Follows every page.
 */
export function getMarketsRegionIdOrders(transport: Transport, params: GetMarketsRegionIdOrdersParams): AsyncIterable<MarketsRegionIdOrdersGet[number]> {
  return transport.paginate<MarketsRegionIdOrdersGet[number]>(getMarketsRegionIdOrdersMeta, { path: { region_id: params.region_id }, query: { order_type: params.order_type, type_id: params.type_id } });
}

export interface GetCharactersCharacterIdWalletParams {
  /** The ID of the character */
  readonly character_id: CharacterID;
}

export const getCharactersCharacterIdWalletMeta: OperationMeta = {
  operationId: 'GetCharactersCharacterIdWallet',
  method: 'GET',
  path: '/characters/{character_id}/wallet',
  scopes: ["esi-wallet.read_character_wallet.v1"],
  paginated: false,
};

/**
 * Get a character's wallet balance
 *
 * `GET /characters/{character_id}/wallet`, requires `esi-wallet.read_character_wallet.v1`
 */
export function getCharactersCharacterIdWallet(transport: Transport, params: GetCharactersCharacterIdWalletParams): Promise<CharactersCharacterIdWalletGet> {
  return transport.request<CharactersCharacterIdWalletGet>(getCharactersCharacterIdWalletMeta, { path: { character_id: params.character_id }, query: {} });
}

export interface GetUniverseTypesTypeIdParams {
  /** An Eve item type ID */
  readonly type_id: number;
}

export const getUniverseTypesTypeIdMeta: OperationMeta = {
  operationId: 'GetUniverseTypesTypeId',
  method: 'GET',
  path: '/universe/types/{type_id}',
  scopes: [],
  paginated: false,
};

/**
 * Get type information
 *
 * `GET /universe/types/{type_id}`
 */
export function getUniverseTypesTypeId(transport: Transport, params: GetUniverseTypesTypeIdParams): Promise<UniverseTypesTypeIdGet> {
  return transport.request<UniverseTypesTypeIdGet>(getUniverseTypesTypeIdMeta, { path: { type_id: params.type_id }, query: {} });
}

export const postUniverseNamesMeta: OperationMeta = {
  operationId: 'PostUniverseNames',
  method: 'POST',
  path: '/universe/names',
  scopes: [],
  paginated: false,
};

/**
 * Get names and categories for a set of IDs
 *
 * `POST /universe/names`
 */
export function postUniverseNames(transport: Transport, body: readonly number[]): Promise<UniverseNamesPost> {
  return transport.request<UniverseNamesPost>(postUniverseNamesMeta, { path: {}, query: {}, body });
}
