import { z } from 'zod';
import { EndpointMap } from './EndpointDefinition';
import {
  CharacterInfoSchema,
  CharacterPortraitSchema,
  AgentResearchSchema,
  BlueprintSchema,
  CorporationHistorySchema,
  JumpFatigueSchema,
  MedalSchema,
  NotificationSchema,
  StandingSchema,
  CharacterTitleSchema,
  CharacterRoleSchema,
} from '../../schemas/character';

export const characterEndpoints = {
  getCharacterPublicInfo: {
    path: 'characters/{characterId}/',
    method: 'GET',
    requiresAuth: false,
    pathParams: ['characterId'],
    responseSchema: CharacterInfoSchema,
  },
  getAgentsResearch: {
    path: 'characters/{characterId}/agents_research/',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['characterId'],
    responseSchema: z.array(AgentResearchSchema),
  },
  getBlueprints: {
    path: 'characters/{characterId}/blueprints/',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['characterId'],
    responseSchema: z.array(BlueprintSchema),
  },
  getRoles: {
    path: 'characters/{characterId}/roles',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['characterId'],
    responseSchema: CharacterRoleSchema,
  },
  getStandings: {
    path: 'characters/{characterId}/standings',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['characterId'],
    responseSchema: z.array(StandingSchema),
  },
  getTitles: {
    path: 'characters/{characterId}/titles',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['characterId'],
    responseSchema: z.array(CharacterTitleSchema),
  },
  getContactNotifications: {
    path: 'characters/{characterId}/notifications/contacts/',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['characterId'],
  },
  getCorporationHistory: {
    path: 'characters/{characterId}/corporationhistory/',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['characterId'],
    responseSchema: z.array(CorporationHistorySchema),
  },
  getJumpFatigue: {
    path: 'characters/{characterId}/fatigue/',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['characterId'],
    responseSchema: JumpFatigueSchema,
  },
  getMedals: {
    path: 'characters/{characterId}/medals/',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['characterId'],
    responseSchema: z.array(MedalSchema),
  },
  getNotifications: {
    path: 'characters/{characterId}/notifications/',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['characterId'],
    responseSchema: z.array(NotificationSchema),
  },
  getPortrait: {
    path: 'characters/{characterId}/portrait/',
    method: 'GET',
    requiresAuth: false,
    pathParams: ['characterId'],
    responseSchema: CharacterPortraitSchema,
  },
  postCharacterAffiliation: {
    path: 'characters/affiliation',
    method: 'POST',
    requiresAuth: false,
    hasBody: true,
  },
  calculateCspaChargeCost: {
    path: 'characters/{characterId}/cspa/',
    method: 'POST',
    requiresAuth: true,
    pathParams: ['characterId'],
    hasBody: true,
  },
} as const satisfies EndpointMap;
