import { EndpointMap } from './EndpointDefinition';

export const corporationEndpoints = {
  getCorporationInfo: {
    path: 'corporations/{corporationId}',
    method: 'GET',
    requiresAuth: false,
    pathParams: ['corporationId'],
  },
  getCorporationAllianceHistory: {
    path: 'corporations/{corporationId}/alliancehistory',
    method: 'GET',
    requiresAuth: false,
    pathParams: ['corporationId'],
  },
  getCorporationBlueprints: {
    path: 'corporations/{corporationId}/blueprints',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['corporationId'],
  },
  getCorporationAlscLogs: {
    path: 'corporations/{corporationId}/containers/logs',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['corporationId'],
  },
  getCorporationDivisions: {
    path: 'corporations/{corporationId}/divisions',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['corporationId'],
  },
  getCorporationFacilities: {
    path: 'corporations/{corporationId}/facilities',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['corporationId'],
  },
  getCorporationIcon: {
    path: 'corporations/{corporationId}/icons',
    method: 'GET',
    requiresAuth: false,
    pathParams: ['corporationId'],
  },
  getCorporationMedals: {
    path: 'corporations/{corporationId}/medals',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['corporationId'],
  },
  getCorporationIssuedMedals: {
    path: 'corporations/{corporationId}/medals/issued',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['corporationId'],
  },
  getCorporationMembers: {
    path: 'corporations/{corporationId}/members',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['corporationId'],
  },
  getCorporationMemberLimit: {
    path: 'corporations/{corporationId}/members/limit',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['corporationId'],
  },
  getCorporationMembersTitles: {
    path: 'corporations/{corporationId}/members/titles',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['corporationId'],
  },
  getCorporationMemberTracking: {
    path: 'corporations/{corporationId}/membertracking',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['corporationId'],
  },
  getCorporationMemberRoles: {
    path: 'corporations/{corporationId}/roles',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['corporationId'],
  },
  getCorporationMemberRolesHistory: {
    path: 'corporations/{corporationId}/roles/history',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['corporationId'],
  },
  getCorporationShareholders: {
    path: 'corporations/{corporationId}/shareholders',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['corporationId'],
  },
  getCorporationStandings: {
    path: 'corporations/{corporationId}/standings',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['corporationId'],
  },
  getCorporationStarbases: {
    path: 'corporations/{corporationId}/starbases',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['corporationId'],
  },
  getCorporationStarbaseDetail: {
    path: 'corporations/{corporationId}/starbases/{starbaseId}',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['corporationId', 'starbaseId'],
  },
  getCorporationStructures: {
    path: 'corporations/{corporationId}/structures',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['corporationId'],
  },
  getCorporationTitles: {
    path: 'corporations/{corporationId}/titles',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['corporationId'],
  },
  getNpcCorporations: {
    path: 'corporations/npccorps',
    method: 'GET',
    requiresAuth: false,
  },
} as const satisfies EndpointMap;
