// Auto-generated from ESI OpenAPI spec — do not edit manually
// Total scopes: 70
// Endpoints requiring scopes: 127

export type EsiScope =
  | 'esi-access.read_lists.v1'
  | 'esi-activities.read_character.v1'
  | 'esi-alliances.read_contacts.v1'
  | 'esi-assets.read_assets.v1'
  | 'esi-assets.read_corporation_assets.v1'
  | 'esi-calendar.read_calendar_events.v1'
  | 'esi-calendar.respond_calendar_events.v1'
  | 'esi-characters.read_agents_research.v1'
  | 'esi-characters.read_blueprints.v1'
  | 'esi-characters.read_contacts.v1'
  | 'esi-characters.read_corporation_roles.v1'
  | 'esi-characters.read_fatigue.v1'
  | 'esi-characters.read_freelance_jobs.v1'
  | 'esi-characters.read_fw_stats.v1'
  | 'esi-characters.read_loyalty.v1'
  | 'esi-characters.read_medals.v1'
  | 'esi-characters.read_notifications.v1'
  | 'esi-characters.read_standings.v1'
  | 'esi-characters.read_titles.v1'
  | 'esi-characters.write_contacts.v1'
  | 'esi-clones.read_clones.v1'
  | 'esi-clones.read_implants.v1'
  | 'esi-contracts.read_character_contracts.v1'
  | 'esi-contracts.read_corporation_contracts.v1'
  | 'esi-corporations.read_blueprints.v1'
  | 'esi-corporations.read_contacts.v1'
  | 'esi-corporations.read_container_logs.v1'
  | 'esi-corporations.read_corporation_membership.v1'
  | 'esi-corporations.read_divisions.v1'
  | 'esi-corporations.read_facilities.v1'
  | 'esi-corporations.read_freelance_jobs.v1'
  | 'esi-corporations.read_fw_stats.v1'
  | 'esi-corporations.read_medals.v1'
  | 'esi-corporations.read_projects.v1'
  | 'esi-corporations.read_standings.v1'
  | 'esi-corporations.read_starbases.v1'
  | 'esi-corporations.read_structures.v1'
  | 'esi-corporations.read_titles.v1'
  | 'esi-corporations.track_members.v1'
  | 'esi-fittings.read_fittings.v1'
  | 'esi-fittings.write_fittings.v1'
  | 'esi-fleets.read_fleet.v1'
  | 'esi-fleets.write_fleet.v1'
  | 'esi-industry.read_character_jobs.v1'
  | 'esi-industry.read_character_mining.v1'
  | 'esi-industry.read_corporation_jobs.v1'
  | 'esi-industry.read_corporation_mining.v1'
  | 'esi-killmails.read_corporation_killmails.v1'
  | 'esi-killmails.read_killmails.v1'
  | 'esi-location.read_location.v1'
  | 'esi-location.read_online.v1'
  | 'esi-location.read_ship_type.v1'
  | 'esi-mail.organize_mail.v1'
  | 'esi-mail.read_mail.v1'
  | 'esi-mail.send_mail.v1'
  | 'esi-markets.read_character_orders.v1'
  | 'esi-markets.read_corporation_orders.v1'
  | 'esi-markets.structure_markets.v1'
  | 'esi-planets.manage_planets.v1'
  | 'esi-planets.read_customs_offices.v1'
  | 'esi-search.search_structures.v1'
  | 'esi-skills.read_skillqueue.v1'
  | 'esi-skills.read_skills.v1'
  | 'esi-structures.read_character.v1'
  | 'esi-structures.read_corporation.v1'
  | 'esi-ui.open_window.v1'
  | 'esi-ui.write_waypoint.v1'
  | 'esi-universe.read_structures.v1'
  | 'esi-wallet.read_character_wallet.v1'
  | 'esi-wallet.read_corporation_wallets.v1';

export const esiEndpointScopes: Record<string, EsiScope[]> = {
  'GET:alliances/{alliance_id}/contacts': ['esi-alliances.read_contacts.v1'],
  'GET:alliances/{alliance_id}/contacts/labels': ['esi-alliances.read_contacts.v1'],
  'GET:characters/{character_id}/agents_research': ['esi-characters.read_agents_research.v1'],
  'GET:characters/{character_id}/assets': ['esi-assets.read_assets.v1'],
  'POST:characters/{character_id}/assets/locations': ['esi-assets.read_assets.v1'],
  'POST:characters/{character_id}/assets/names': ['esi-assets.read_assets.v1'],
  'GET:characters/{character_id}/attributes': ['esi-skills.read_skills.v1'],
  'GET:characters/{character_id}/blueprints': ['esi-characters.read_blueprints.v1'],
  'GET:characters/{character_id}/calendar': ['esi-calendar.read_calendar_events.v1'],
  'GET:characters/{character_id}/calendar/{event_id}': ['esi-calendar.read_calendar_events.v1'],
  'PUT:characters/{character_id}/calendar/{event_id}': ['esi-calendar.respond_calendar_events.v1'],
  'GET:characters/{character_id}/calendar/{event_id}/attendees': ['esi-calendar.read_calendar_events.v1'],
  'GET:characters/{character_id}/clones': ['esi-clones.read_clones.v1'],
  'GET:characters/{character_id}/contacts': ['esi-characters.read_contacts.v1'],
  'POST:characters/{character_id}/contacts': ['esi-characters.write_contacts.v1'],
  'PUT:characters/{character_id}/contacts': ['esi-characters.write_contacts.v1'],
  'DELETE:characters/{character_id}/contacts': ['esi-characters.write_contacts.v1'],
  'GET:characters/{character_id}/contacts/labels': ['esi-characters.read_contacts.v1'],
  'GET:characters/{character_id}/contracts': ['esi-contracts.read_character_contracts.v1'],
  'GET:characters/{character_id}/contracts/{contract_id}/bids': ['esi-contracts.read_character_contracts.v1'],
  'GET:characters/{character_id}/contracts/{contract_id}/items': ['esi-contracts.read_character_contracts.v1'],
  'POST:characters/{character_id}/cspa': ['esi-characters.read_contacts.v1'],
  'GET:characters/{character_id}/fatigue': ['esi-characters.read_fatigue.v1'],
  'GET:characters/{character_id}/fittings': ['esi-fittings.read_fittings.v1'],
  'POST:characters/{character_id}/fittings': ['esi-fittings.write_fittings.v1'],
  'DELETE:characters/{character_id}/fittings/{fitting_id}': ['esi-fittings.write_fittings.v1'],
  'GET:characters/{character_id}/fleet': ['esi-fleets.read_fleet.v1'],
  'GET:characters/{character_id}/freelance-jobs': ['esi-characters.read_freelance_jobs.v1'],
  'GET:characters/{character_id}/freelance-jobs/{job_id}/participation': ['esi-characters.read_freelance_jobs.v1'],
  'GET:characters/{character_id}/fw/stats': ['esi-characters.read_fw_stats.v1'],
  'GET:characters/{character_id}/implants': ['esi-clones.read_implants.v1'],
  'GET:characters/{character_id}/industry/jobs': ['esi-industry.read_character_jobs.v1'],
  'GET:characters/{character_id}/killmails/recent': ['esi-killmails.read_killmails.v1'],
  'GET:characters/{character_id}/location': ['esi-location.read_location.v1'],
  'GET:characters/{character_id}/loyalty/points': ['esi-characters.read_loyalty.v1'],
  'GET:characters/{character_id}/mail': ['esi-mail.read_mail.v1'],
  'POST:characters/{character_id}/mail': ['esi-mail.send_mail.v1'],
  'GET:characters/{character_id}/mail/{mail_id}': ['esi-mail.read_mail.v1'],
  'PUT:characters/{character_id}/mail/{mail_id}': ['esi-mail.organize_mail.v1'],
  'DELETE:characters/{character_id}/mail/{mail_id}': ['esi-mail.organize_mail.v1'],
  'GET:characters/{character_id}/mail/labels': ['esi-mail.read_mail.v1'],
  'POST:characters/{character_id}/mail/labels': ['esi-mail.organize_mail.v1'],
  'DELETE:characters/{character_id}/mail/labels/{label_id}': ['esi-mail.organize_mail.v1'],
  'GET:characters/{character_id}/mail/lists': ['esi-mail.read_mail.v1'],
  'GET:characters/{character_id}/medals': ['esi-characters.read_medals.v1'],
  'GET:characters/{character_id}/mining': ['esi-industry.read_character_mining.v1'],
  'GET:characters/{character_id}/notifications': ['esi-characters.read_notifications.v1'],
  'GET:characters/{character_id}/notifications/contacts': ['esi-characters.read_notifications.v1'],
  'GET:characters/{character_id}/online': ['esi-location.read_online.v1'],
  'GET:characters/{character_id}/orders': ['esi-markets.read_character_orders.v1'],
  'GET:characters/{character_id}/orders/history': ['esi-markets.read_character_orders.v1'],
  'GET:characters/{character_id}/planets': ['esi-planets.manage_planets.v1'],
  'GET:characters/{character_id}/planets/{planet_id}': ['esi-planets.manage_planets.v1'],
  'GET:characters/{character_id}/roles': ['esi-characters.read_corporation_roles.v1'],
  'GET:characters/{character_id}/search': ['esi-search.search_structures.v1'],
  'GET:characters/{character_id}/ship': ['esi-location.read_ship_type.v1'],
  'GET:characters/{character_id}/skillqueue': ['esi-skills.read_skillqueue.v1'],
  'GET:characters/{character_id}/skills': ['esi-skills.read_skills.v1'],
  'GET:characters/{character_id}/standings': ['esi-characters.read_standings.v1'],
  'GET:characters/{character_id}/titles': ['esi-characters.read_titles.v1'],
  'GET:characters/{character_id}/wallet': ['esi-wallet.read_character_wallet.v1'],
  'GET:characters/{character_id}/wallet/journal': ['esi-wallet.read_character_wallet.v1'],
  'GET:characters/{character_id}/wallet/transactions': ['esi-wallet.read_character_wallet.v1'],
  'GET:corporation/{corporation_id}/mining/extractions': ['esi-industry.read_corporation_mining.v1'],
  'GET:corporation/{corporation_id}/mining/observers': ['esi-industry.read_corporation_mining.v1'],
  'GET:corporation/{corporation_id}/mining/observers/{observer_id}': ['esi-industry.read_corporation_mining.v1'],
  'GET:corporations/{corporation_id}/assets': ['esi-assets.read_corporation_assets.v1'],
  'POST:corporations/{corporation_id}/assets/locations': ['esi-assets.read_corporation_assets.v1'],
  'POST:corporations/{corporation_id}/assets/names': ['esi-assets.read_corporation_assets.v1'],
  'GET:corporations/{corporation_id}/blueprints': ['esi-corporations.read_blueprints.v1'],
  'GET:corporations/{corporation_id}/contacts': ['esi-corporations.read_contacts.v1'],
  'GET:corporations/{corporation_id}/contacts/labels': ['esi-corporations.read_contacts.v1'],
  'GET:corporations/{corporation_id}/containers/logs': ['esi-corporations.read_container_logs.v1'],
  'GET:corporations/{corporation_id}/contracts': ['esi-contracts.read_corporation_contracts.v1'],
  'GET:corporations/{corporation_id}/contracts/{contract_id}/bids': ['esi-contracts.read_corporation_contracts.v1'],
  'GET:corporations/{corporation_id}/contracts/{contract_id}/items': ['esi-contracts.read_corporation_contracts.v1'],
  'GET:corporations/{corporation_id}/customs_offices': ['esi-planets.read_customs_offices.v1'],
  'GET:corporations/{corporation_id}/divisions': ['esi-corporations.read_divisions.v1'],
  'GET:corporations/{corporation_id}/facilities': ['esi-corporations.read_facilities.v1'],
  'GET:corporations/{corporation_id}/freelance-jobs': ['esi-corporations.read_freelance_jobs.v1'],
  'GET:corporations/{corporation_id}/freelance-jobs/{job_id}/participants': ['esi-corporations.read_freelance_jobs.v1'],
  'GET:corporations/{corporation_id}/fw/stats': ['esi-corporations.read_fw_stats.v1'],
  'GET:corporations/{corporation_id}/industry/jobs': ['esi-industry.read_corporation_jobs.v1'],
  'GET:corporations/{corporation_id}/killmails/recent': ['esi-killmails.read_corporation_killmails.v1'],
  'GET:corporations/{corporation_id}/medals': ['esi-corporations.read_medals.v1'],
  'GET:corporations/{corporation_id}/medals/issued': ['esi-corporations.read_medals.v1'],
  'GET:corporations/{corporation_id}/members': ['esi-corporations.read_corporation_membership.v1'],
  'GET:corporations/{corporation_id}/members/limit': ['esi-corporations.track_members.v1'],
  'GET:corporations/{corporation_id}/members/titles': ['esi-corporations.read_titles.v1'],
  'GET:corporations/{corporation_id}/membertracking': ['esi-corporations.track_members.v1'],
  'GET:corporations/{corporation_id}/orders': ['esi-markets.read_corporation_orders.v1'],
  'GET:corporations/{corporation_id}/orders/history': ['esi-markets.read_corporation_orders.v1'],
  'GET:corporations/{corporation_id}/projects': ['esi-corporations.read_projects.v1'],
  'GET:corporations/{corporation_id}/projects/{project_id}': ['esi-corporations.read_projects.v1'],
  'GET:corporations/{corporation_id}/projects/{project_id}/contribution/{character_id}': ['esi-corporations.read_projects.v1'],
  'GET:corporations/{corporation_id}/projects/{project_id}/contributors': ['esi-corporations.read_projects.v1'],
  'GET:corporations/{corporation_id}/roles': ['esi-corporations.read_corporation_membership.v1'],
  'GET:corporations/{corporation_id}/roles/history': ['esi-corporations.read_corporation_membership.v1'],
  'GET:corporations/{corporation_id}/shareholders': ['esi-wallet.read_corporation_wallets.v1'],
  'GET:corporations/{corporation_id}/standings': ['esi-corporations.read_standings.v1'],
  'GET:corporations/{corporation_id}/starbases': ['esi-corporations.read_starbases.v1'],
  'GET:corporations/{corporation_id}/starbases/{starbase_id}': ['esi-corporations.read_starbases.v1'],
  'GET:corporations/{corporation_id}/structures': ['esi-corporations.read_structures.v1'],
  'GET:corporations/{corporation_id}/titles': ['esi-corporations.read_titles.v1'],
  'GET:corporations/{corporation_id}/wallets': ['esi-wallet.read_corporation_wallets.v1'],
  'GET:corporations/{corporation_id}/wallets/{division}/journal': ['esi-wallet.read_corporation_wallets.v1'],
  'GET:corporations/{corporation_id}/wallets/{division}/transactions': ['esi-wallet.read_corporation_wallets.v1'],
  'GET:fleets/{fleet_id}': ['esi-fleets.read_fleet.v1'],
  'PUT:fleets/{fleet_id}': ['esi-fleets.write_fleet.v1'],
  'GET:fleets/{fleet_id}/members': ['esi-fleets.read_fleet.v1'],
  'POST:fleets/{fleet_id}/members': ['esi-fleets.write_fleet.v1'],
  'PUT:fleets/{fleet_id}/members/{member_id}': ['esi-fleets.write_fleet.v1'],
  'DELETE:fleets/{fleet_id}/members/{member_id}': ['esi-fleets.write_fleet.v1'],
  'PUT:fleets/{fleet_id}/squads/{squad_id}': ['esi-fleets.write_fleet.v1'],
  'DELETE:fleets/{fleet_id}/squads/{squad_id}': ['esi-fleets.write_fleet.v1'],
  'GET:fleets/{fleet_id}/wings': ['esi-fleets.read_fleet.v1'],
  'POST:fleets/{fleet_id}/wings': ['esi-fleets.write_fleet.v1'],
  'PUT:fleets/{fleet_id}/wings/{wing_id}': ['esi-fleets.write_fleet.v1'],
  'DELETE:fleets/{fleet_id}/wings/{wing_id}': ['esi-fleets.write_fleet.v1'],
  'POST:fleets/{fleet_id}/wings/{wing_id}/squads': ['esi-fleets.write_fleet.v1'],
  'GET:markets/structures/{structure_id}': ['esi-markets.structure_markets.v1'],
  'POST:ui/autopilot/waypoint': ['esi-ui.write_waypoint.v1'],
  'POST:ui/openwindow/contract': ['esi-ui.open_window.v1'],
  'POST:ui/openwindow/information': ['esi-ui.open_window.v1'],
  'POST:ui/openwindow/marketdetails': ['esi-ui.open_window.v1'],
  'POST:ui/openwindow/newmail': ['esi-ui.open_window.v1'],
  'GET:universe/structures/{structure_id}': ['esi-universe.read_structures.v1'],
};
