import { z } from 'zod';
import { EndpointMap } from './EndpointDefinition';
import {
  AncestrySchema,
  AsteroidBeltInfoSchema,
  BloodlineSchema,
  BulkIdResultSchema,
  ConstellationInfoSchema,
  FactionSchema,
  GraphicInfoSchema,
  ItemCategorySchema,
  ItemGroupSchema,
  MoonInfoSchema,
  NameAndCategorySchema,
  PlanetInfoSchema,
  RaceSchema,
  RegionInfoSchema,
  SchematicInfoSchema,
  SolarSystemInfoSchema,
  StarInfoSchema,
  StargateInfoSchema,
  StationInfoSchema,
  StructureInfoSchema,
  SystemJumpSchema,
  SystemKillSchema,
  TypeInfoSchema,
} from '../../schemas/universe';

export const universeEndpoints = {
  getAncestries: {
    path: 'universe/ancestries',
    method: 'GET',
    requiresAuth: false,
    responseSchema: z.array(AncestrySchema),
  },
  getAsteroidBeltInfo: {
    path: 'universe/asteroid_belts/{asteroidBeltId}',
    method: 'GET',
    requiresAuth: false,
    pathParams: ['asteroidBeltId'],
    responseSchema: AsteroidBeltInfoSchema,
  },
  getBloodlines: {
    path: 'universe/bloodlines',
    method: 'GET',
    requiresAuth: false,
    responseSchema: z.array(BloodlineSchema),
  },
  getCategories: {
    path: 'universe/categories',
    method: 'GET',
    requiresAuth: false,
  },
  getCategoryById: {
    path: 'universe/categories/{categoryId}',
    method: 'GET',
    requiresAuth: false,
    pathParams: ['categoryId'],
    responseSchema: ItemCategorySchema,
  },
  getConstellations: {
    path: 'universe/constellations',
    method: 'GET',
    requiresAuth: false,
  },
  getConstellationById: {
    path: 'universe/constellations/{constellationId}',
    method: 'GET',
    requiresAuth: false,
    pathParams: ['constellationId'],
    responseSchema: ConstellationInfoSchema,
  },
  getFactions: {
    path: 'universe/factions',
    method: 'GET',
    requiresAuth: false,
    responseSchema: z.array(FactionSchema),
  },
  getGraphics: {
    path: 'universe/graphics',
    method: 'GET',
    requiresAuth: false,
  },
  getGraphicById: {
    path: 'universe/graphics/{graphicId}',
    method: 'GET',
    requiresAuth: false,
    pathParams: ['graphicId'],
    responseSchema: GraphicInfoSchema,
  },
  getItemGroups: {
    path: 'universe/groups',
    method: 'GET',
    requiresAuth: false,
  },
  getItemGroupById: {
    path: 'universe/groups/{groupId}',
    method: 'GET',
    requiresAuth: false,
    pathParams: ['groupId'],
    responseSchema: ItemGroupSchema,
  },
  postBulkNamesToIds: {
    path: 'universe/ids',
    method: 'POST',
    requiresAuth: false,
    bodyBuilder: (names: string[]) => names,
    responseSchema: BulkIdResultSchema,
  },
  getMoonById: {
    path: 'universe/moons/{moonId}',
    method: 'GET',
    requiresAuth: false,
    pathParams: ['moonId'],
    responseSchema: MoonInfoSchema,
  },
  postNamesAndCategories: {
    path: 'universe/names',
    method: 'POST',
    requiresAuth: false,
    bodyBuilder: (ids: number[]) => ids,
    responseSchema: z.array(NameAndCategorySchema),
  },
  getPlanetById: {
    path: 'universe/planets/{planetId}',
    method: 'GET',
    requiresAuth: false,
    pathParams: ['planetId'],
    responseSchema: PlanetInfoSchema,
  },
  getRaces: {
    path: 'universe/races',
    method: 'GET',
    requiresAuth: false,
    responseSchema: z.array(RaceSchema),
  },
  getRegions: {
    path: 'universe/regions',
    method: 'GET',
    requiresAuth: false,
  },
  getRegionById: {
    path: 'universe/regions/{regionId}',
    method: 'GET',
    requiresAuth: false,
    pathParams: ['regionId'],
    responseSchema: RegionInfoSchema,
  },
  getSchematicById: {
    path: 'universe/schematics/{schematicId}',
    method: 'GET',
    requiresAuth: false,
    pathParams: ['schematicId'],
    responseSchema: SchematicInfoSchema,
  },
  getStargateById: {
    path: 'universe/stargates/{stargateId}',
    method: 'GET',
    requiresAuth: false,
    pathParams: ['stargateId'],
    responseSchema: StargateInfoSchema,
  },
  getStarById: {
    path: 'universe/stars/{starId}',
    method: 'GET',
    requiresAuth: false,
    pathParams: ['starId'],
    responseSchema: StarInfoSchema,
  },
  getStationById: {
    path: 'universe/stations/{stationId}',
    method: 'GET',
    requiresAuth: false,
    pathParams: ['stationId'],
    responseSchema: StationInfoSchema,
  },
  getStructures: {
    path: 'universe/structures',
    method: 'GET',
    requiresAuth: false,
  },
  getStructureById: {
    path: 'universe/structures/{structureId}',
    method: 'GET',
    requiresAuth: true,
    pathParams: ['structureId'],
    responseSchema: StructureInfoSchema,
  },
  getSystemJumps: {
    path: 'universe/system_jumps',
    method: 'GET',
    requiresAuth: false,
    responseSchema: z.array(SystemJumpSchema),
  },
  getSystemKills: {
    path: 'universe/system_kills',
    method: 'GET',
    requiresAuth: false,
    responseSchema: z.array(SystemKillSchema),
  },
  getSystems: {
    path: 'universe/systems',
    method: 'GET',
    requiresAuth: false,
  },
  getSystemById: {
    path: 'universe/systems/{systemId}',
    method: 'GET',
    requiresAuth: false,
    pathParams: ['systemId'],
    responseSchema: SolarSystemInfoSchema,
  },
  getTypes: {
    path: 'universe/types',
    method: 'GET',
    requiresAuth: false,
  },
  getTypeById: {
    path: 'universe/types/{typeId}',
    method: 'GET',
    requiresAuth: false,
    pathParams: ['typeId'],
    responseSchema: TypeInfoSchema,
  },
} as const satisfies EndpointMap;
