/**
 * The consumer matrix: the checks `scripts/quality/consumer-contract.ts` runs against
 * an installed tarball, separated from the CLI so the Jest fixture suite
 * (`tests/tdd/consumer-contract/`) can run the same checks against small,
 * deliberately broken packages.
 *
 * A **cell** is one way a TypeScript project consumes the package: a module
 * format (an ES module `.mts` file or a CommonJS `.cts` file) under one
 * `moduleResolution` (`node16`, `nodenext` or `bundler`). Each cell is its
 * own `tsc` program with `skipLibCheck: false`, so the shipped declarations
 * are checked as that consumer resolves them. The TypeScript version and the
 * Node version are the other two axes; the CLI takes the first as an option
 * and CI chooses the second.
 *
 * Every cell includes a generated **probe** that imports every documented
 * sub-path, so a sub-path that stops resolving fails every cell, and asserts
 * the module format the types claim: under node16 and nodenext an ES module
 * consumer must not see a synthesised `default` export, which is what
 * CommonJS declarations behind the `import` condition give it (esi-23g.29).
 *
 * The runtime probe loads every documented sub-path through `require` and
 * `import` on the running Node. The tree-shaking check bundles one named
 * import from a light sub-path with esbuild and fails if code only a heavy
 * sub-path needs comes with it.
 */
import { spawnSync } from 'child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'fs';
import * as path from 'path';

export const PACKAGE_NAME = '@lgriffin/esi.ts';

/**
 * The sub-paths guides/SEMVER.md documents as public, besides
 * `./package.json`. The packed `exports` map must list exactly these.
 */
export const DOCUMENTED_SUBPATHS = [
  '.',
  './schemas',
  './errors',
  './testing',
  './client',
  './sde',
  './sde/memory',
] as const;

/**
 * The oldest TypeScript the package supports. zod 4's declarations use
 * `NoInfer`, added in TypeScript 5.4, and the `cjs-bundler` cell needs
 * `module: preserve`, also 5.4. Declared in README.md and
 * guides/SEMVER.md; raising it is an environment change.
 */
export const OLDEST_TYPESCRIPT = '5.4.5';

export type ModuleFormat = 'esm' | 'cjs';
export type Resolution = 'node16' | 'nodenext' | 'bundler';

export interface Cell {
  id: string;
  format: ModuleFormat;
  resolution: Resolution;
}

export const CELLS: readonly Cell[] = (
  ['node16', 'nodenext', 'bundler'] as const
).flatMap((resolution) =>
  (['esm', 'cjs'] as const).map((format) => ({
    id: `${format}-${resolution}`,
    format,
    resolution,
  })),
);

export function specifierFor(packageName: string, subpath: string): string {
  return subpath === '.' ? packageName : `${packageName}/${subpath.slice(2)}`;
}

// ---------------------------------------------------------------------------
// The exports map
// ---------------------------------------------------------------------------

/** Differences between the packed `exports` keys and the documented list. */
export function exportsProblems(
  manifest: { exports?: unknown },
  documented: readonly string[],
): string[] {
  const exportsMap =
    manifest.exports && typeof manifest.exports === 'object'
      ? (manifest.exports as Record<string, unknown>)
      : {};
  const packed = Object.keys(exportsMap).filter((k) => k !== './package.json');
  return [
    ...documented
      .filter((s) => !packed.includes(s))
      .map((s) => `documented sub-path ${s} is missing from exports`),
    ...packed
      .filter((s) => !documented.includes(s))
      .map((s) => `exports has undocumented sub-path ${s}`),
  ];
}

// ---------------------------------------------------------------------------
// Type-check cells
// ---------------------------------------------------------------------------

export const PROBE_DIR = 'probe';

/**
 * The generated probe for one module format. The ES module probe imports
 * every sub-path as a namespace and asserts that no namespace type has a
 * `default` member; the runtime ES module has none. The CommonJS probe uses
 * `import x = require()`, which resolves through the `require` condition
 * under every resolution, including bundler with `module: preserve`.
 */
export function probeSource(
  format: ModuleFormat,
  packageName: string,
  subpaths: readonly string[],
): string {
  const lines = [
    `// Generated by scripts/quality/consumer-contract-core.ts for ${packageName}.`,
  ];
  subpaths.forEach((subpath, i) => {
    const specifier = specifierFor(packageName, subpath);
    lines.push(
      format === 'esm'
        ? `import * as m${i} from '${specifier}';`
        : `import m${i} = require('${specifier}');`,
    );
  });
  lines.push(
    "type HasDefault<M> = 'default' extends keyof M ? true : false;",
    '// Each sub-path exports something a consumer can name.',
    'type HasExports<M> = [keyof M] extends [never] ? false : true;',
  );
  const tuple = (type: string) =>
    subpaths.map((_, i) => `${type}<typeof m${i}>`).join(', ');
  const values = (value: string) => subpaths.map(() => value).join(', ');
  lines.push(
    `export const hasExports: [${tuple('HasExports')}] = [${values('true')}];`,
  );
  if (format === 'esm') {
    lines.push(
      '// An ES module has no default export unless it declares one.',
      `export const noSynthesisedDefault: [${tuple('HasDefault')}] = [${values('false')}];`,
    );
  }
  return `${lines.join('\n')}\n`;
}

export function probeFile(format: ModuleFormat): string {
  return `${PROBE_DIR}/${format === 'esm' ? 'probe.mts' : 'probe.cts'}`;
}

/** Write both probes into `consumerDir/probe/`. */
export function writeProbes(
  consumerDir: string,
  packageName: string,
  subpaths: readonly string[],
): void {
  mkdirSync(path.join(consumerDir, PROBE_DIR), { recursive: true });
  for (const format of ['esm', 'cjs'] as const) {
    writeFileSync(
      path.join(consumerDir, probeFile(format)),
      probeSource(format, packageName, subpaths),
    );
  }
}

export interface CellOptions {
  /** Extra consumer files for the cell, relative to the consumer directory. */
  files?: readonly string[];
  /** Whether the cell type-checks the generated probe (default true). */
  probe?: boolean;
  /** `compilerOptions.types`; `[]` when `@types/node` is not installed. */
  types?: readonly string[];
}

/** The tsconfig for one cell. Nothing is emitted. */
export function cellTsconfig(
  cell: Cell,
  options: CellOptions = {},
): Record<string, unknown> {
  const module =
    cell.resolution === 'bundler'
      ? // `preserve` keeps `import x = require()` legal in the .cts probe, and
        // resolves it through `require` as a bundler would.
        cell.format === 'cjs'
        ? 'preserve'
        : 'esnext'
      : cell.resolution;
  return {
    compilerOptions: {
      target: 'es2022',
      module,
      moduleResolution: cell.resolution,
      strict: true,
      skipLibCheck: false,
      noEmit: true,
      // The consumers read `@lgriffin/esi.ts/package.json`.
      resolveJsonModule: true,
      types: [...(options.types ?? ['node'])],
    },
    files: [
      ...(options.probe === false ? [] : [probeFile(cell.format)]),
      ...(options.files ?? []),
    ],
  };
}

// ---------------------------------------------------------------------------
// Upstream breaks
// ---------------------------------------------------------------------------

/**
 * The diagnostics in a `tsc` output, each as `file(line,col): error TSnnnn`
 * with the path's separators normalised, or null when the output has no
 * error, when any error has no file position, or when any lies outside
 * node_modules (the probe, the control). Two outputs fail the same way when
 * their keys match.
 */
export function errorDiagnostics(output: string): Set<string> | null {
  const errorLines = output
    .split(/\r?\n/)
    .filter((line) => /\berror TS\d+/.test(line));
  if (errorLines.length === 0) return null;
  const diagnostics = new Set<string>();
  for (const line of errorLines) {
    const match = /^(\S[^(\n]*)\((\d+),(\d+)\): error (TS\d+)/.exec(line);
    if (!match) return null;
    const file = match[1]!.replace(/\\/g, '/');
    if (!/(?:^|\/)node_modules\//.test(file)) return null;
    diagnostics.add(`${file}(${match[2]},${match[3]}): error ${match[4]}`);
  }
  return diagnostics;
}

/** The control file for a module format: `.mts` for ESM, `.cts` for CJS. */
export function controlFile(format: ModuleFormat): string {
  return `${PROBE_DIR}/control.${format === 'esm' ? 'mts' : 'cts'}`;
}

/**
 * A consumer that imports only this package's runtime dependencies, in the
 * given module format. When it fails to type-check the same way a cell of
 * that format does, the break is in those packages and the TypeScript
 * version, not in this package's declarations.
 */
export function controlSource(
  dependencies: readonly string[],
  format: ModuleFormat = 'esm',
): string {
  const lines = [
    '// Generated by scripts/quality/consumer-contract-core.ts: the runtime dependencies alone.',
  ];
  dependencies.forEach((dependency, i) => {
    lines.push(
      format === 'esm'
        ? `import * as d${i} from '${dependency}';`
        : `import d${i} = require('${dependency}');`,
    );
  });
  lines.push(
    `export type Dependencies = [${dependencies.map((_, i) => `typeof d${i}`).join(', ')}];`,
  );
  return `${lines.join('\n')}\n`;
}

/**
 * Whether a failed cell is an upstream break: every error is a diagnostic in
 * a dependency's own declarations (never this package's), and the control
 * for the same format and resolution, which imports those dependencies
 * without this package, reports each of those diagnostics too.
 */
export function isUpstreamBreak(
  cellOutput: string,
  controlOutput: string | null,
  packageName: string,
): boolean {
  const cell = errorDiagnostics(cellOutput);
  if (cell === null || controlOutput === null) return false;
  if ([...cell].some((d) => d.includes(`node_modules/${packageName}/`))) {
    return false;
  }
  const control = errorDiagnostics(controlOutput);
  return control !== null && [...cell].every((d) => control.has(d));
}

export interface CellResult {
  cell: Cell;
  ok: boolean;
  output: string;
  /** Failed only on a dependency's own declarations (see isUpstreamBreak). */
  upstream?: boolean;
}

/**
 * Type-check one cell with the `tsc` of the TypeScript installed in the
 * consumer (or `tsc`, when given). Spawns the CLI rather than calling the
 * compiler API: TypeScript 7 ships no stable JavaScript API.
 */
export function typeCheckCell(
  consumerDir: string,
  cell: Cell,
  options: CellOptions & { tsc?: string } = {},
): CellResult {
  const config = `tsconfig.${cell.id}.json`;
  writeFileSync(
    path.join(consumerDir, config),
    `${JSON.stringify(cellTsconfig(cell, options), null, 2)}\n`,
  );
  const tsc =
    options.tsc ??
    path.join(consumerDir, 'node_modules', 'typescript', 'bin', 'tsc');
  const result = spawnSync(process.execPath, [tsc, '-p', config], {
    cwd: consumerDir,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
    maxBuffer: 64 * 1024 * 1024,
  });
  if (result.error) throw result.error;
  return {
    cell,
    ok: result.status === 0,
    output: `${result.stdout ?? ''}${result.stderr ?? ''}`.trim(),
  };
}

// ---------------------------------------------------------------------------
// Runtime probe
// ---------------------------------------------------------------------------

/** An ES module script that loads every sub-path through require and import. */
export function runtimeProbeSource(
  packageName: string,
  subpaths: readonly string[],
): string {
  return `// Generated by scripts/quality/consumer-contract-core.ts.
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const specifiers = ${JSON.stringify(subpaths.map((s) => specifierFor(packageName, s)))};
const failures = [];
for (const specifier of specifiers) {
  for (const [condition, load] of [
    ['require', async () => require(specifier)],
    ['import', () => import(specifier)],
  ]) {
    try {
      const mod = await load();
      const names = Object.keys(mod).filter((k) => k !== 'default' && k !== '__esModule');
      if (names.length === 0) failures.push(\`\${specifier} (\${condition}) exports nothing\`);
    } catch (err) {
      failures.push(\`\${specifier} (\${condition}): \${err && err.code ? err.code + ' ' : ''}\${err instanceof Error ? err.message.split('\\n')[0] : String(err)}\`);
    }
  }
}
if (failures.length > 0) {
  console.error(failures.join('\\n'));
  process.exit(1);
}
console.log(\`runtime: \${specifiers.length} sub-paths load through require and import\`);
`;
}

export function runRuntimeProbe(
  consumerDir: string,
  packageName: string,
  subpaths: readonly string[],
): { ok: boolean; output: string } {
  const file = path.join(consumerDir, PROBE_DIR, 'runtime.mjs');
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, runtimeProbeSource(packageName, subpaths));
  const result = spawnSync(process.execPath, [file], {
    cwd: consumerDir,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  });
  if (result.error) throw result.error;
  return {
    ok: result.status === 0,
    output: `${result.stdout ?? ''}${result.stderr ?? ''}`.trim(),
  };
}

// ---------------------------------------------------------------------------
// Tree shaking
// ---------------------------------------------------------------------------

/** The parts of esbuild's API the check uses. */
export interface EsbuildLike {
  buildSync(options: Record<string, unknown>): {
    outputFiles?: Array<{ text: string }>;
    metafile?: { inputs: Record<string, unknown> };
  };
  /** Ends esbuild's worker, which holds its binary open on Windows. */
  stop?(): void | Promise<void>;
}

export interface TreeShakeOptions {
  consumerDir: string;
  esbuild: EsbuildLike;
  packageName: string;
  /** A named import from the sub-path that must stay small. */
  light: { subpath: string; name: string };
  /** A named import from the sub-path whose code must not come along. */
  heavy: { subpath: string; name: string };
  /** A string only the heavy sub-path's code contains. */
  marker: string;
  /** The light bundle's ceiling, in bytes. */
  maxBytes: number;
  external: readonly string[];
}

export interface TreeShakeResult {
  ok: boolean;
  problems: string[];
  lightBytes: number;
  heavyBytes: number;
}

/**
 * Bundle `import { name } from '<sub-path>'` for the light and the heavy
 * sub-path, as an application bundler would (esbuild, ES module output,
 * minified, dependencies external). The heavy bundle is the control: it must
 * contain the marker, or the marker proves nothing. The light bundle must not
 * contain the marker, must not include the heavy sub-path's entry file, and
 * must stay under `maxBytes`.
 */
export function treeShakeCheck(options: TreeShakeOptions): TreeShakeResult {
  const bundle = (entry: { subpath: string; name: string }) => {
    const specifier = specifierFor(options.packageName, entry.subpath);
    const result = options.esbuild.buildSync({
      stdin: {
        contents: `import { ${entry.name} } from '${specifier}';\nconsole.log(${entry.name});\n`,
        resolveDir: options.consumerDir,
        loader: 'js',
      },
      bundle: true,
      write: false,
      format: 'esm',
      platform: 'node',
      minify: true,
      metafile: true,
      logLevel: 'silent',
      external: [...options.external],
    });
    return {
      text: result.outputFiles?.[0]?.text ?? '',
      inputs: Object.keys(result.metafile?.inputs ?? {}).map((f) =>
        f.split(path.sep).join('/'),
      ),
    };
  };

  const light = bundle(options.light);
  const heavy = bundle(options.heavy);
  const problems: string[] = [];
  const lightSpecifier = specifierFor(
    options.packageName,
    options.light.subpath,
  );
  const heavySpecifier = specifierFor(
    options.packageName,
    options.heavy.subpath,
  );

  if (!heavy.text.includes(options.marker)) {
    problems.push(
      `control: the ${heavySpecifier} bundle does not contain the marker ${JSON.stringify(options.marker)}, so its absence proves nothing`,
    );
  }
  if (light.text.includes(options.marker)) {
    problems.push(
      `${lightSpecifier} bundle contains ${JSON.stringify(options.marker)} from ${heavySpecifier}`,
    );
  }
  const heavyEntry = importTarget(
    options.consumerDir,
    options.packageName,
    options.heavy.subpath,
  );
  if (!heavyEntry || !heavy.inputs.some((f) => f.endsWith(heavyEntry))) {
    problems.push(
      `control: the ${heavySpecifier} bundle does not include its entry file ${heavyEntry ?? '(no import target in exports)'}`,
    );
  } else if (light.inputs.some((f) => f.endsWith(heavyEntry))) {
    problems.push(
      `${lightSpecifier} bundle includes ${heavyEntry}, the entry file of ${heavySpecifier}`,
    );
  }
  if (light.text.length > options.maxBytes) {
    problems.push(
      `${lightSpecifier} bundle is ${light.text.length} B, over its ${options.maxBytes} B ceiling`,
    );
  }
  return {
    ok: problems.length === 0,
    problems,
    lightBytes: light.text.length,
    heavyBytes: heavy.text.length,
  };
}

/**
 * `node_modules/<package>/<file>` for the `import` target of a sub-path in
 * the installed package's `exports` map, or null when it has none.
 */
export function importTarget(
  consumerDir: string,
  packageName: string,
  subpath: string,
): string | null {
  const manifest = JSON.parse(
    readFileSync(
      path.join(consumerDir, 'node_modules', packageName, 'package.json'),
      'utf8',
    ),
  ) as { exports?: Record<string, unknown> };
  const entry = manifest.exports?.[subpath];
  let target: unknown =
    entry && typeof entry === 'object'
      ? (entry as Record<string, unknown>).import
      : undefined;
  if (target && typeof target === 'object') {
    target = (target as Record<string, unknown>).default;
  }
  return typeof target === 'string'
    ? `node_modules/${packageName}/${target.replace(/^\.\//, '')}`
    : null;
}
