import { existsSync, readFileSync } from 'node:fs';
import { defineConfig, type DefaultTheme } from 'vitepress';

/**
 * The site for https://lgriffin.github.io/ESI.ts/ (CHARTER DOC-03).
 *
 * guide/ and examples/ are generated by `npm run docs:sync` from guides/,
 * README.md and examples/ (scripts/docs/sync-docs.ts), with the sidebar in
 * sidebar.generated.json; api/ is TypeDoc's output in public/api, copied
 * as-is. `npm run docs:site` builds all three. Only this file, the theme and
 * index.md are written by hand.
 */

const REPO = 'https://github.com/lgriffin/ESI.ts';

// The version selector reads package.json, so it cannot go stale (REL-03).
// `npm run validate:versions -- --site` checks the built page carries it.
const pkg = JSON.parse(
  readFileSync(new URL('../../package.json', import.meta.url), 'utf8'),
) as { version: string };

const sidebarFile = new URL('./sidebar.generated.json', import.meta.url);
const sidebar: DefaultTheme.SidebarMulti = existsSync(sidebarFile)
  ? JSON.parse(readFileSync(sidebarFile, 'utf8'))
  : {};

/**
 * GitHub's heading anchors, so a guide's `USAGE.md#8-examples` link keeps
 * working on the site: lower case, punctuation dropped, spaces to hyphens.
 */
function githubSlug(text: string): string {
  return text
    .trim()
    .toLowerCase()
    .replace(/<[^>]*>/g, '')
    .replace(/[^\p{L}\p{N}\s_-]/gu, '')
    .replace(/\s/g, '-');
}

export default defineConfig({
  title: 'ESI.ts',
  description:
    'A typed, validated and resilient TypeScript client for the EVE Online ESI API',
  base: '/ESI.ts/',
  cleanUrls: true,
  lastUpdated: false,
  // TypeDoc copies the Markdown files the README links to into public/api/media;
  // they are files to serve, not pages to build.
  srcExclude: ['public/**'],
  head: [
    ['link', { rel: 'icon', type: 'image/svg+xml', href: '/ESI.ts/logo.svg' }],
  ],

  // /api/ is TypeDoc's static output, not a VitePress page; localhost links
  // are the SSO callback an example listens on.
  ignoreDeadLinks: [/^\/api(\/|$)/, /^https?:\/\/localhost[:/]/],

  markdown: {
    anchor: { slugify: githubSlug },
  },

  themeConfig: {
    logo: '/logo.svg',

    nav: [
      { text: 'Guide', link: '/guide/', activeMatch: '^/guide/' },
      { text: 'Examples', link: '/examples/', activeMatch: '^/examples/' },
      { text: 'API Reference', link: '/api/', target: '_self' },
      {
        text: `v${pkg.version}`,
        items: [
          { text: 'Changelog', link: `${REPO}/blob/master/CHANGELOG.md` },
          { text: 'Releases', link: `${REPO}/releases` },
          {
            text: 'npm',
            link: 'https://www.npmjs.com/package/@lgriffin/esi.ts',
          },
        ],
      },
    ],

    sidebar,

    socialLinks: [
      { icon: 'github', link: REPO },
      { icon: 'npm', link: 'https://www.npmjs.com/package/@lgriffin/esi.ts' },
    ],

    search: { provider: 'local' },

    editLink: {
      // Generated pages carry their source in `sourceFile`; edit that. The
      // function runs in the browser, so it names the repository itself.
      pattern: ({ filePath, frontmatter }) =>
        `https://github.com/lgriffin/ESI.ts/edit/master/${
          typeof frontmatter.sourceFile === 'string'
            ? frontmatter.sourceFile
            : `docs-site/${filePath}`
        }`,
      text: 'Edit this page on GitHub',
    },

    footer: {
      message: 'Released under the GPL-3.0-or-later license.',
      copyright: 'Copyright © 2024-present Leigh Griffin',
    },

    outline: { level: [2, 3] },
  },
});
