export {
  EsiError,
  TimeoutError,
  EsiValidationError,
  EsiNetworkError,
  EsiFaultError,
  EsiConfigurationError,
  EsiParseError,
  EsiPaginationError,
  EsiTokenRefreshError,
  isEsiError,
  isRateLimited,
  isNotFound,
  isUnauthorized,
  isForbidden,
  isServerError,
  isTimeout,
  isRetryable,
  isValidationError,
  isCircuitOpen,
  isNetworkError,
  isFaultError,
  isConfigurationError,
  isParseError,
  isPaginationError,
  isTokenRefreshError,
  sanitizeUrl,
  CircuitOpenError,
} from './core/util/error';
export type { ValidationDirection, EsiFaultCode } from './core/util/error';

export {
  AuthError,
  SsoError,
  TokenRevokedError,
  TokenDecodeError,
  CharacterNotFoundError,
  isAuthError,
  isSsoError,
  isTokenRevoked,
  isCharacterNotFound,
} from './auth/errors';
